import React from "react";
import "../css/InternshipCertificate.css";

function InternshipCertificate({ assignment, totalHours, onBack }) {
  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="certificate-page">

      {/* =====================================================
          TOP ACTION BUTTONS
      ===================================================== */}
      <div className="no-print certificate-actions">

        <button onClick={handlePrint}>
          🖨️ Print / Save as PDF
        </button>

        <button onClick={onBack}>
          ← Back to My Internship
        </button>

      </div>


      {/* =====================================================
          CERTIFICATE
      ===================================================== */}
      <div className="certificate">

        <div className="certificate-border">

          {/* HEADER */}
          <div className="certificate-header">

            <h1>INTERLINK</h1>

            <p>
              FYUGP INTERNSHIP MANAGEMENT SYSTEM
            </p>

          </div>


          {/* TITLE */}
          <div className="certificate-title">

            <h2>
              INTERNSHIP COMPLETION CERTIFICATE
            </h2>

            <p>
              This certificate is generated by InterLink
            </p>

          </div>


          {/* MAIN CONTENT */}
          <div className="certificate-body">

            <p className="certificate-intro">
              This is to certify that
            </p>

            <h3 className="student-name">
              {assignment.student?.name || "Student"}
            </h3>

            <p>
              Register Number:{" "}
              <strong>
                {assignment.student?.registerNumber || "N/A"}
              </strong>
            </p>

            <p className="certificate-text">
              has successfully completed the internship programme at
            </p>

            <h3 className="company-name">
              {assignment.company?.companyName || "Company"}
            </h3>

            <p>
              Internship / Position:{" "}
              <strong>
                {assignment.internship?.title || "N/A"}
              </strong>
            </p>

            <p>
              Required Duration:{" "}
              <strong>
                {assignment.internship?.duration || "N/A"}
              </strong>
            </p>

            <p>
              Total Hours Completed:{" "}
              <strong>
                {totalHours} hours
              </strong>
            </p>


            {/* DETAILS */}
            <div className="certificate-details">

              <div>
                <strong>Faculty Guide</strong>

                <p>
                  {assignment.facultyGuide?.name || "N/A"}
                </p>
              </div>


              <div>
                <strong>Company Guide</strong>

                <p>
                  {assignment.companyGuide?.name || "N/A"}
                </p>
              </div>


              <div>
                <strong>Mark</strong>

                <p>
                  {assignment.mark !== null &&
                  assignment.mark !== undefined
                    ? assignment.mark
                    : "N/A"}
                </p>
              </div>


              <div>
                <strong>Credits</strong>

                <p>
                  {assignment.credits || 0}
                </p>
              </div>

            </div>


            {/* FOOTER TEXT */}
            <p className="certificate-footer-text">
              This certificate records the successful completion
              of the internship in the InterLink system.
            </p>

          </div>


          {/* =================================================
              SIGNATURES + SEAL
          ================================================= */}
          <div className="certificate-bottom">

            <div className="signature">

              <div className="signature-line"></div>

              <p>
                InterLink System
              </p>

            </div>


            <div className="certificate-seal">
              INTERLINK
            </div>


            <div className="signature">

              <div className="signature-line"></div>

              <p>
                Faculty Guide
              </p>

            </div>

          </div>

        </div>

      </div>

    </div>
  );
}

export default InternshipCertificate;